version: '3.1'

services:
  db:
    image: mysql:latest
    container_name: product_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: product_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "5432:5432"
